trigger:
- main

pool:
    vmImage: ubuntu-latest

variables:
- name: dockerHubRepository
  value: 'taniaduggal60/taskonepane'
- name: dockerfilePath
  value: 'Dockerfile'
- name: System.Debug
  value: true

jobs:
- job: BuildAndPush
  displayName: 'Build and Push to Docker Hub'
  steps:
    
  - task: Docker@2
    displayName: 'Build Docker image'
    inputs:
      containerRegistry: 'docker'
      repository: $(dockerHubRepository)
      command: 'build'
      Dockerfile: $(dockerfilePath)
      buildContext: '.'
      tags: '$(Build.BuildId)'

  - task: Docker@2
    displayName: 'Push Docker image to Docker Hub'
    inputs:
      containerRegistry: 'docker' 
      repository: $(dockerHubRepository)
      command: 'push'
      tags: '$(Build.BuildId)'
