trigger:
- main

pool:
  name: Azure Pipelines

variables:
- name: dockerHubRepository
  value: 'taniaduggal60/taskonepane'
- name: dockerfilePath
  value: 'Dockerfile'
- name: System.Debug
  value: true

- task: Go@0
  inputs:
    command: 'build'
    
- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    containerRegistry: 'docker'
    repository: $(dockerHubRepository)
    command: 'build'
    Dockerfile: $(dockerfilePath)
    buildContext: '.'
    tags: '$(Build.BuildId)'

- task: Docker@2
  displayName: 'Push Docker image to Docker Hub'
  inputs:
    containerRegistry: 'docker' //serviceconnectionname
    repository: $(dockerHubRepository)
    command: 'push'
    tags: '$(Build.BuildId)'