trigger:
- main

pool:
  name: Azure Pipelines

variables:
- name: dockerHubRepository
  value: 'taniaduggal60/taskonepane'
- name: dockerfilePath
  value: 'Dockerfile'
- name: System.Debug
  value: true
- name: DOCKERHUB_USERNAME
  value: ''
- name: DOCKERHUB_PASSWORD
  value: ''


jobs:
- job: BuildAndPush
  displayName: 'Build and Push to Docker Hub'
  steps:
    

  - task: Docker@2
    displayName: 'Login to Docker Hub'
    inputs:
      server: 'docker.io'
      repository: $(dockerHubRepository)
      command: 'login'
      username: $(DOCKERHUB_USERNAME)
      password: $(DOCKERHUB_PASSWORD)

  - task: Docker@2
    displayName: 'Build Docker image'
    inputs:
      server: 'docker.io'
      repository: $(dockerHubRepository)
      command: 'build'
      Dockerfile: $(dockerfilePath)
      buildContext: '.'
      tags: '$(Build.BuildId)'

  - task: Docker@2
    displayName: 'Push Docker image to Docker Hub'
    inputs:
      server: 'docker.io' 
      repository: $(dockerHubRepository)
      command: 'push'
      tags: '$(Build.BuildId)'
  

